<h2>Add new blog post</h2>
<?php
/** @var \Zend\Form\Form $form */
$form = $this->form;
$form->prepare();
echo $this->form()->openTag($form); // <form action="" method="" ...

?>

<div class="form-group">
    <?php echo $this->formRow($form->get('title')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('slug')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('content')); ?>
</div>
<div class="form-group">
    <?php echo $this->formRow($form->get('category')); ?>
</div>

<?php echo $this->formSubmit($form->get('submit')); ?>
<?php echo $this->form()->closeTag(); ?>